### ISSUE TITLE
Material UI and react 18.2.0

### ISSUE THREAD

**Issue by Neeraj-Sr** [Azure-Samples/azure-search-javascript-samples#44]
it appears that material ui 4.12.4 has been deprecated and no longer supported with react 18.2.0. npm install gives dependency error.
Has anyone been able to successfully build this project?

**Comment by HeidiSteen** [comment]
Hi @Neeraj-Sr, there are two samples in this repo.  I just tested the quickstart right now and it runs for me. I deleted the package-lock.json file before running the program, and I removed that file from the project so it's no longer part of the download.

I didn't test the second sample today, but it was fully revised about 2 months ago. If you're running into issues with the second sample, can you reply back?  For now, I'm going to assume the issues was with the quickstart.  I'm closing the issue, but feel free to reopen it if there is more work to do here.
